"""create initial tables

Revision ID: d3bc00b81c27
Revises: 
Create Date: 2026-03-09 01:10:16.835407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc00b81c27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sskedata.accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sskedata'
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_number', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number'),
    schema='sskedata'
    )
    op.create_table('product_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('priceperunit', sa.Numeric(), nullable=True),
    sa.Column('totalprice', sa.Numeric(), nullable=True),
    sa.Column('lastupdatetimestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('stock_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reference_invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['sskedata.customers.id'], ),
    sa.ForeignKeyConstraint(['reference_invoice_id'], ['sskedata.invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    schema='sskedata'
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(), nullable=True),
    sa.Column('credit', sa.Numeric(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sskedata.accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['sskedata.journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('hsncode', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['sskedata.product_brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['sskedata.product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['sskedata.product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['sskedata.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['sskedata.customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sskedata.invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['sskedata.journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('product_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('batch_code', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('remaining_qty', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('discount_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['sskedata.products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sskedata.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('tax_percent', sa.Numeric(), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('reference_item_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['sskedata.product_batches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sskedata.invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['sskedata.products.id'], ),
    sa.ForeignKeyConstraint(['reference_item_id'], ['sskedata.invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sskedata'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items', schema='sskedata')
    op.drop_table('product_batches', schema='sskedata')
    op.drop_table('payments', schema='sskedata')
    op.drop_table('discounts', schema='sskedata')
    op.drop_table('products', schema='sskedata')
    op.drop_table('journal_lines', schema='sskedata')
    op.drop_table('invoices', schema='sskedata')
    op.drop_table('suppliers', schema='sskedata')
    op.drop_table('stock_summary', schema='sskedata')
    op.drop_table('stock', schema='sskedata')
    op.drop_table('product_categories', schema='sskedata')
    op.drop_table('product_brands', schema='sskedata')
    op.drop_table('journal_entries', schema='sskedata')
    op.drop_table('customers', schema='sskedata')
    op.drop_table('accounts', schema='sskedata')
    # ### end Alembic commands ###
